"use client";

import Link from "next/link";
import { useState } from "react";
import { demoCollectors, demoRequests } from "../data/platform";

export default function CollectorDashboard() {
  const collector = demoCollectors[0];
  const [tab, setTab] = useState("Overview");
  const [requests, setRequests] = useState(demoRequests);
  const tabs = ["Overview", "Assigned Collections", "Pending Requests", "Collection Locations", "Completed", "Earnings / Points", "Profile"];
  const update = (id:string,status:string) => setRequests((items) => items.map((item) => item.id === id ? {...item,status} : item));
  const list = tab === "Pending Requests" ? requests.filter((item) => item.status === "Pending") : tab === "Completed" ? requests.filter((item) => item.status === "Completed") : requests;
  return <main className="portal"><aside className="portal-sidebar"><Link className="portal-logo" href="/">↻ <b>EcoLoop</b></Link><span className="demo-tag">DEMO COLLECTOR</span><nav>{tabs.map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><Link href="/dashboard">Household dashboard →</Link><Link href="/">← Back to website</Link></aside><section className="portal-content"><header><div><small>COLLECTOR DASHBOARD · SAMPLE DATA</small><h1>{tab}</h1></div><div className="profile-chip"><span>KS</span><div><b>{collector.name}</b><small>✓ Verified Collector</small></div></div></header>{tab === "Overview" && <><div className="metric-grid"><Metric label="Pending Requests" value={String(requests.filter((r)=>r.status==="Pending").length)} icon="⏳"/><Metric label="Assigned Collections" value={String(collector.assigned)} icon="📋"/><Metric label="Completed Collections" value={String(collector.completed)} icon="✓"/><Metric label="Demo Points" value="3,840" icon="🌿"/></div><RequestPanel requests={requests} update={update}/></>}{["Assigned Collections","Pending Requests","Completed"].includes(tab) && <RequestPanel requests={list} update={update}/>} {tab === "Collection Locations" && <article className="portal-panel"><h2>Sample collection route</h2><div className="route-map"><span>📍 Nugegoda</span><i>••••••••</i><span>♻ Kotte</span><i>••••••••</i><span>🚛 Maharagama</span></div><p className="demo-note">Demo locations only. Live routing can connect when verified requests are available.</p></article>}{tab === "Earnings / Points" && <><div className="metric-grid"><Metric label="Demo Collector Points" value="3,840" icon="🌿"/><Metric label="Completed Collections" value="38" icon="✓"/></div><p className="demo-note">No real payments are processed in this frontend demo.</p></>}{tab === "Profile" && <article className="portal-panel collector-profile"><span className="verified-badge">✓ Verified Collector</span><h2>{collector.name}</h2><p>{collector.organization}</p><dl><div><dt>Collector ID</dt><dd>{collector.id}</dd></div><div><dt>Service area</dt><dd>{collector.serviceArea}</dd></div><div><dt>Verification status</dt><dd>{collector.verificationStatus}</dd></div><div><dt>Waste types</dt><dd>{collector.wasteTypes.join(" · ")}</dd></div></dl></article>}</section></main>;
}

function Metric({label,value,icon}:{label:string;value:string;icon:string}) { return <article className="metric-card"><span>{icon}</span><small>{label}</small><strong>{value}</strong></article>; }
function RequestPanel({requests,update}:{requests:typeof demoRequests;update:(id:string,status:string)=>void}) { return <article className="portal-panel"><h2>Collection requests</h2><div className="request-grid">{requests.map((item) => <article key={item.id}><div><small>{item.id}</small><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></div><h3>{item.household}</h3><p>📍 {item.location}</p><p>🕐 {item.date} · {item.time}</p><p>♻ {item.waste} · {item.weight}</p>{item.status === "Pending" && <div className="request-actions"><button onClick={() => update(item.id,"Rejected")}>Reject</button><button onClick={() => update(item.id,"Assigned")}>Accept</button></div>}</article>)}</div></article>; }
