"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Pickup = { id:string; household_name?:string; phone?:string; address:string; waste_type:string; quantity:string; pickup_date:string; pickup_time:string; notes?:string; status:string; collector_id?:string; collector_name?:string; recorded_weight?:number; coins_awarded?:number };
type Collector = { id:string; name:string; phone:string; service_area:string; organization:string; verification_status:string; has_access_key?:number };
type Redemption = { id:string; reward_name:string; points:number; reference:string; created_at:string };
type CollectorState = { profile:Collector; openJobs:Pickup[]; jobs:Pickup[]; redemptions:Redemption[]; balance:number };
type Data = { adminAuthenticated:boolean; household:{ requests:Pickup[] }; collector:CollectorState|null; admin:{ requests:Pickup[]; collectors:Collector[] }|null };
type Response = Data & { error?:string; accessKey?:string };
type Act = (payload:Record<string,unknown>, success:string)=>Promise<Response|null>;
type Role = "household" | "collector" | "admin";
const emptyData:Data = { adminAuthenticated:false, household:{ requests:[] }, collector:null, admin:null };
const rewards = [{ name:"Eco Gift Pack", points:500, icon:"🌱" }, { name:"Shopping Voucher", points:1000, icon:"🛍️" }, { name:"Special Reward", points:1500, icon:"🎁" }];
const dateInputValue = (date:Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function validateNameInput(event:FormEvent<HTMLInputElement>){const input=event.currentTarget;const value=input.value.trim();input.setCustomValidity(!value||(/^[\p{L}\p{M}.' -]+$/u.test(value)&&/\p{L}/u.test(value))?"":"Use letters, spaces, apostrophes and full stops only.");}

export default function SystemPage() {
  const [role,setRole] = useState<Role>(()=>{ if(typeof window==="undefined") return "household"; const value=new URLSearchParams(window.location.search).get("role"); return value&&["household","collector","admin"].includes(value)?value as Role:"household"; });
  const [data,setData] = useState<Data>(emptyData);
  const [loading,setLoading] = useState(true);
  const [busy,setBusy] = useState(false); const [message,setMessage] = useState(""); const [error,setError] = useState("");
  useEffect(()=>{ let active=true; fetch("/api/system",{cache:"no-store"}).then(async response=>{const json=await response.json() as Response;if(!response.ok) throw new Error(json.error);return json;}).then(json=>{if(active)setData(json);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load the system.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;}; },[]);
  const act:Act = async (payload, success)=>{ setBusy(true);setError("");setMessage(""); try{ const response=await fetch("/api/system",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const json=await response.json() as Response; if(!response.ok) throw new Error(json.error); setData(json); setMessage(success); return json; }catch(e){setError(e instanceof Error?e.message:"Action failed.");return null;}finally{setBusy(false);} };

  return <main className="system-shell">
    <header className="system-topbar"><Link href="/" className="system-logo"><span>↻</span><b>EcoLoop</b></Link><div><small>LIVE WORKFLOW</small><strong>Smart Waste Collection System</strong></div><Link href="/">← Home</Link></header>
    <section className="system-hero"><div><p className="kicker">WORKING PROTOTYPE</p><h1>One request. One collector. <em>A cleaner community.</em></h1><p>Households request a pickup for free. Verified collectors complete collections and earn 100 coins per completed job.</p></div><div className="flow-mini"><span>🏠 Request</span><b>→</b><span>🚛 Collect</span><b>→</b><span>🪙 Collector earns</span></div></section>
    <nav className="role-tabs" aria-label="Select demo role">{(["household","collector","admin"] as Role[]).map(r=><button key={r} className={role===r?"active":""} onClick={()=>{setRole(r);setMessage("");setError("");}}>{r==="household"?"🏠 Household":r==="collector"?"🚛 Collector":"🛡️ Admin"}</button>)}</nav>
    <div className="demo-banner">Households see only their own requests. Collectors and admins must sign in to see pickup details.</div>
    {(message||error)&&<div className={error?"system-alert error":"system-alert"}>{error||message}</div>}
    {loading&&<div className="system-alert" role="status" aria-live="polite">Loading system data...</div>}
    {!loading&&role==="household"&&<Household requests={data.household.requests} busy={busy} act={act}/>} 
    {!loading&&role==="collector"&&(data.collector?<CollectorView state={data.collector} busy={busy} act={act}/>:<CollectorAccess busy={busy} act={act}/>)} 
    {!loading&&role==="admin"&&(data.admin?<Admin admin={data.admin} busy={busy} act={act}/>:<AdminLogin busy={busy} act={act}/>)}
  </main>;
}

function Household({requests,busy,act}:{requests:Pickup[];busy:boolean;act:Act}){
  const today=new Date();const minDate=dateInputValue(today);const latest=new Date(today);latest.setDate(latest.getDate()+30);const maxDate=dateInputValue(latest);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const v=Object.fromEntries(new FormData(form));if(await act({action:"createRequest",...v},"Pickup request submitted successfully."))form.reset();}
  return <section className="system-workspace"><div className="system-intro"><div><small>HOUSEHOLD PORTAL</small><h2>Request a waste pickup</h2><p>No fee and no points. Simply schedule your sorted waste for collection.</p></div><span>Free request</span></div><div className="system-columns"><form className="system-card system-form" onSubmit={submit}><h3>Pickup details</h3><label>Full name<input name="householdName" required minLength={2} maxLength={60} onInput={validateNameInput} autoComplete="name" placeholder="e.g. Nimal Perera"/></label><div className="form-pair"><label>Phone<input name="phone" type="tel" inputMode="numeric" required pattern="(?:\+94|0)7[0-9]{8}" title="Enter 10 digits, for example 0771234567." autoComplete="tel" placeholder="0771234567"/></label><label>Waste type<select name="wasteType" required defaultValue=""><option value="" disabled>Select type</option><option>Plastic</option><option>Paper & Cardboard</option><option>Metal</option><option>Glass</option><option>E-Waste</option><option>Organic</option><option>Mixed Recyclables</option></select></label></div><label>Pickup address<textarea name="address" required minLength={8} maxLength={250} autoComplete="street-address" placeholder="House number, road, city"/></label><div className="form-pair"><label>Estimated weight (kg)<input name="quantity" type="number" inputMode="decimal" required min="0.1" max="1000" step="0.1" placeholder="e.g. 3.5"/></label><label>Preferred date<input name="pickupDate" type="date" min={minDate} max={maxDate} required/></label></div><div className="form-pair"><label>Preferred time<input name="pickupTime" type="time" required/></label><label>Notes<input name="notes" maxLength={200} placeholder="Gate colour, landmark…"/></label></div><small className="form-help">Pickup date must be within the next 30 days.</small><button className="system-primary" disabled={busy}>♻ Submit pickup request</button></form><div className="system-card"><h3>My requests</h3><RequestList requests={requests}/></div></div></section>
}

function AccessKeyNotice({accessKey}:{accessKey:string}){return accessKey?<div className="system-alert" role="status">Your collector access key: <code>{accessKey}</code> — save it now. You need it with your phone number to sign in on another device, and it will not be shown again.</div>:null}

function CollectorAccess({busy,act}:{busy:boolean;act:Act}){
  const [accessKey,setAccessKey]=useState("");
  async function register(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const json=await act({action:"registerCollector",...Object.fromEntries(new FormData(form))},"Registration sent for admin verification.");if(json){form.reset();setAccessKey(json.accessKey||"");}}
  function login(e:FormEvent<HTMLFormElement>){e.preventDefault();void act({action:"collectorLogin",...Object.fromEntries(new FormData(e.currentTarget))},"Signed in as collector.");}
  return <section className="system-workspace"><AccessKeyNotice accessKey={accessKey}/><div className="collector-head"><div><small>COLLECTOR PORTAL</small><h2>Collection jobs & rewards</h2><p>Register once, then sign in with your phone number and access key.</p></div></div>
    <div className="system-columns"><form className="system-card system-form compact" onSubmit={register}><h3>Register as a collector</h3><label>Name<input name="name" required minLength={2} maxLength={60} onInput={validateNameInput} autoComplete="name"/></label><label>Phone<input name="phone" type="tel" inputMode="numeric" required pattern="(?:\+94|0)7[0-9]{8}" title="Enter 10 digits, for example 0771234567." autoComplete="tel" placeholder="0771234567"/></label><label>Service area<input name="serviceArea" required minLength={2} maxLength={80} placeholder="e.g. Chilaw"/></label><label>Organization<input name="organization" maxLength={100} placeholder="Independent Collector"/></label><button className="system-primary" disabled={busy}>Send for verification</button></form>
    <form className="system-card system-form compact" onSubmit={login}><h3>Collector sign in</h3><label>Phone<input name="phone" type="tel" inputMode="numeric" required pattern="(?:\+94|0)7[0-9]{8}" title="Enter 10 digits, for example 0771234567." autoComplete="tel" placeholder="0771234567"/></label><label>Access key<input name="accessKey" type="password" required minLength={32} maxLength={40} autoComplete="current-password"/></label><small className="form-help">Lost your key? Ask an EcoLoop admin to issue a new one.</small><button className="system-primary" disabled={busy}>Sign in</button></form></div>
  </section>
}

function CollectorView({state,busy,act}:{state:CollectorState;busy:boolean;act:Act}){
  const {profile,openJobs,jobs,balance}=state;const verified=profile.verification_status==="Verified";
  const assigned=jobs.filter(r=>r.status==="Scheduled");const completed=jobs.filter(r=>r.status==="Completed");
  return <section className="system-workspace"><div className="collector-head"><div><small>COLLECTOR PORTAL</small><h2>Collection jobs & rewards</h2><p>100 coins are credited only after a scheduled pickup is completed.</p></div><div className="coin-card"><small>AVAILABLE BALANCE</small><strong>🪙 {balance}</strong><span>Collector coins</span></div></div>
    <div className="collector-select"><div><b>{profile.name}</b> · {profile.service_area} · {profile.phone}</div><span className={verified?"status completed":"status pending"}>{profile.verification_status}</span><button type="button" className="admin-logout" disabled={busy} onClick={()=>void act({action:"collectorLogout"},"Signed out.")}>Log out</button></div>
    <div className="system-card wide"><h3>Available pickup requests</h3>{!verified?<Empty text="Open pickups appear once an admin verifies your profile."/>:openJobs.length===0?<Empty text="No open pickup requests right now."/>:<div className="job-list job-grid">{openJobs.map(r=><article key={r.id}><div><b>{r.waste_type}</b><span className="status pending">Pending</span></div><p>📍 {r.address}</p><small>{r.pickup_date} · {r.pickup_time} · {r.quantity}</small><button disabled={busy} onClick={()=>void act({action:"acceptRequest",requestId:r.id},"Pickup accepted.")}>Accept job</button></article>)}</div>}</div>
    <div className="system-card wide"><h3>My scheduled collections</h3>{assigned.length===0?<Empty text="Accepted jobs will appear here."/>:<div className="job-list job-grid">{assigned.map(r=><article key={r.id}><div><b>{r.household_name}</b><span className="status scheduled">Scheduled</span></div><p>{r.address}</p><small>{r.pickup_date} · {r.pickup_time} · 📞 {r.phone}{r.notes?` · ${r.notes}`:""}</small><CompleteForm request={r} busy={busy} act={act}/></article>)}</div>}</div>
    <div className="rewards-system"><div><p className="kicker">COLLECTOR REWARDS</p><h2>Redeem your coins</h2><p>Households do not earn Eco Points. These rewards are exclusively for verified collection work.</p></div><div className="system-reward-grid">{rewards.map(r=><article key={r.name}><span>{r.icon}</span><h3>{r.name}</h3><strong>{r.points} coins</strong><button disabled={busy||!verified||balance<r.points} onClick={()=>void act({action:"redeem",rewardName:r.name},`${r.name} redeemed successfully.`)}>{balance>=r.points?"Redeem":"More coins needed"}</button></article>)}</div>{completed.length>0&&<p className="completion-note">✓ {completed.length} completed collection{completed.length===1?"":"s"} · {completed.length*100} coins earned before redemptions</p>}</div>
  </section>
}

function CompleteForm({request,busy,act}:{request:Pickup;busy:boolean;act:Act}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const v=Object.fromEntries(new FormData(f));void act({action:"completeRequest",requestId:request.id,...v},"Collection completed — 100 coins added.");}return <form className="complete-form" onSubmit={submit}><select name="wasteType" defaultValue={request.waste_type}><option>Plastic</option><option>Paper & Cardboard</option><option>Metal</option><option>Glass</option><option>E-Waste</option><option>Organic</option><option>Mixed Recyclables</option></select><input name="weight" type="number" min="0.1" max="1000" step="0.1" required placeholder="Weight (kg)"/><button disabled={busy}>Complete +100</button></form>}

function AdminLogin({busy,act}:{busy:boolean;act:Act}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;void act({action:"adminLogin",...Object.fromEntries(new FormData(form))},"Admin login successful.");}return <section className="system-workspace admin-login-wrap"><form className="system-card system-form admin-login" onSubmit={submit}><span className="admin-lock">🔐</span><small>PROTECTED ADMIN PORTAL</small><h2>Admin login</h2><p>Enter the administrator password to verify collectors and manage pickup requests.</p><label>Password<input name="password" type="password" required minLength={12} autoComplete="current-password"/></label><button className="system-primary" disabled={busy}>{busy?"Signing in…":"Sign in securely"}</button></form></section>}

function Admin({admin,busy,act}:{admin:{requests:Pickup[];collectors:Collector[]};busy:boolean;act:Act}){
  const [accessKey,setAccessKey]=useState("");const waiting=admin.collectors.filter(c=>c.verification_status!=="Verified");
  async function issueKey(c:Collector){const json=await act({action:"issueCollectorKey",collectorId:c.id},`New access key issued for ${c.name}. Share it with them privately.`);if(json)setAccessKey(json.accessKey||"");}
  return <section className="system-workspace"><AccessKeyNotice accessKey={accessKey}/><div className="system-intro"><div><small>ADMIN PORTAL</small><h2>Verify and monitor operations</h2><p>Collector approval protects households and unlocks job acceptance.</p></div><div className="admin-tools"><div className="admin-metrics"><span><b>{admin.requests.length}</b> requests</span><span><b>{admin.collectors.length}</b> collectors</span><span><b>{admin.requests.filter(r=>r.status==="Completed").length}</b> completed</span></div><button type="button" className="admin-logout" disabled={busy} onClick={()=>void act({action:"adminLogout"},"Admin logged out.")}>Log out</button></div></div>
    <div className="system-columns"><div className="system-card"><h3>Collector verification</h3>{waiting.length===0?<Empty text="No collectors are waiting for verification."/>:<div className="job-list">{waiting.map(c=><article key={c.id}><div><b>{c.name}</b><span className="status pending">Pending</span></div><p>{c.organization} · {c.service_area}</p><small>{c.phone}</small><button disabled={busy} onClick={()=>void act({action:"verifyCollector",collectorId:c.id},`${c.name} is now verified.`)}>Verify collector</button></article>)}</div>}</div><div className="system-card"><h3>All pickup requests</h3><RequestList requests={admin.requests} admin busy={busy} act={act}/></div></div>
    <div className="system-card wide"><h3>Collector access keys</h3>{admin.collectors.length===0?<Empty text="No collectors registered yet."/>:<div className="job-list job-grid">{admin.collectors.map(c=><article key={c.id}><div><b>{c.name}</b><span className={c.verification_status==="Verified"?"status completed":"status pending"}>{c.verification_status}</span></div><p>{c.phone} · {c.service_area}</p><small>{c.has_access_key?"Access key set":"No access key yet — issue one so this collector can sign in"}</small><button disabled={busy} onClick={()=>void issueKey(c)}>{c.has_access_key?"Reset access key":"Issue access key"}</button></article>)}</div>}</div>
  </section>}

function RequestList({requests,admin=false,busy=false,act}:{requests:Pickup[];admin?:boolean;busy?:boolean;act?:Act}){return requests.length===0?<Empty text="No pickup requests yet."/>:<div className="request-list">{requests.map(r=><article key={r.id}><div><b>{r.waste_type}</b><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></div><p>{r.household_name} · {r.address}{admin&&r.phone?` · ${r.phone}`:""}</p><small>{r.pickup_date} at {r.pickup_time}{r.collector_name?` · ${r.collector_name}`:""}</small>{admin&&act&&r.status==="Pending"&&<div className="job-list"><button disabled={busy} onClick={()=>void act({action:"rejectRequest",requestId:r.id},"Pickup request cancelled.")}>Cancel request</button></div>}</article>)}</div>}
function Empty({text}:{text:string}){return <div className="system-empty"><span>♻</span><p>{text}</p></div>}
