"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Pickup = { id:string; household_name:string; phone:string; address:string; waste_type:string; quantity:string; pickup_date:string; pickup_time:string; notes?:string; status:string; collector_id?:string; collector_name?:string; recorded_weight?:number; coins_awarded:number };
type Collector = { id:string; name:string; phone:string; service_area:string; organization:string; verification_status:string };
type Redemption = { id:string; collector_id:string; reward_name:string; points:number; reference:string; created_at:string };
type Data = { requests:Pickup[]; collectors:Collector[]; redemptions:Redemption[] };
type Role = "household" | "collector" | "admin";
const rewards = [{ name:"Eco Gift Pack", points:500, icon:"🌱" }, { name:"Shopping Voucher", points:1000, icon:"🛍️" }, { name:"Special Reward", points:1500, icon:"🎁" }];

export default function SystemPage() {
  const [role,setRole] = useState<Role>(()=>{ if(typeof window==="undefined") return "household"; const value=new URLSearchParams(window.location.search).get("role"); return value&&["household","collector","admin"].includes(value)?value as Role:"household"; });
  const [data,setData] = useState<Data>({requests:[],collectors:[],redemptions:[]});
  const [collectorId,setCollectorId] = useState("");
  const [busy,setBusy] = useState(false); const [message,setMessage] = useState(""); const [error,setError] = useState("");
  useEffect(()=>{ let active=true; fetch("/api/system",{cache:"no-store"}).then(async response=>{const json=await response.json();if(!response.ok) throw new Error(json.error);return json;}).then(json=>{if(!active)return;setData(json);setCollectorId(json.collectors?.[0]?.id||"");}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load the system.");});return()=>{active=false;}; },[]);
  async function act(payload:Record<string,unknown>, success:string){ setBusy(true);setError("");setMessage(""); try{ const response=await fetch("/api/system",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const json=await response.json(); if(!response.ok) throw new Error(json.error); setData(json); setCollectorId((current)=>current || json.collectors?.[0]?.id || ""); setMessage(success); }catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);} }
  const collector=data.collectors.find(c=>c.id===collectorId); const assigned=data.requests.filter(r=>r.collector_id===collectorId);
  const balance=useMemo(()=>assigned.filter(r=>r.status==="Completed").reduce((n,r)=>n+Number(r.coins_awarded||0),0)-data.redemptions.filter(r=>r.collector_id===collectorId).reduce((n,r)=>n+Number(r.points),0),[assigned,data.redemptions,collectorId]);

  return <main className="system-shell">
    <header className="system-topbar"><Link href="/" className="system-logo"><span>↻</span><b>EcoLoop</b></Link><div><small>LIVE WORKFLOW</small><strong>Smart Waste Collection System</strong></div><Link href="/">← Home</Link></header>
    <section className="system-hero"><div><p className="kicker">WORKING PROTOTYPE</p><h1>One request. One collector. <em>A cleaner community.</em></h1><p>Households request a pickup for free. Verified collectors complete collections and earn 100 coins per completed job.</p></div><div className="flow-mini"><span>🏠 Request</span><b>→</b><span>🚛 Collect</span><b>→</b><span>🪙 Collector earns</span></div></section>
    <nav className="role-tabs" aria-label="Select demo role">{(["household","collector","admin"] as Role[]).map(r=><button key={r} className={role===r?"active":""} onClick={()=>{setRole(r);setMessage("");setError("");}}>{r==="household"?"🏠 Household":r==="collector"?"🚛 Collector":"🛡️ Admin"}</button>)}</nav>
    <div className="demo-banner">Demo role switch: use all three views to test the complete workflow. Real sign-in can be connected later.</div>
    {(message||error)&&<div className={error?"system-alert error":"system-alert"}>{error||message}</div>}
    {role==="household"&&<Household data={data} busy={busy} act={act}/>} 
    {role==="collector"&&<CollectorView data={data} collector={collector} collectorId={collectorId} setCollectorId={setCollectorId} balance={balance} busy={busy} act={act}/>} 
    {role==="admin"&&<Admin data={data} busy={busy} act={act}/>} 
  </main>;
}

function Household({data,busy,act}:{data:Data;busy:boolean;act:(p:Record<string,unknown>,s:string)=>Promise<void>}){
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const v=Object.fromEntries(new FormData(form));void act({action:"createRequest",...v},"Pickup request submitted successfully.").then(()=>form.reset());}
  return <section className="system-workspace"><div className="system-intro"><div><small>HOUSEHOLD PORTAL</small><h2>Request a waste pickup</h2><p>No fee and no points. Simply schedule your sorted waste for collection.</p></div><span>Free request</span></div><div className="system-columns"><form className="system-card system-form" onSubmit={submit}><h3>Pickup details</h3><label>Full name<input name="householdName" required placeholder="e.g. Nimal Perera"/></label><div className="form-pair"><label>Phone<input name="phone" required placeholder="07X XXX XXXX"/></label><label>Waste type<select name="wasteType" required defaultValue=""><option value="" disabled>Select type</option><option>Plastic</option><option>Paper & Cardboard</option><option>Metal</option><option>Glass</option><option>E-Waste</option><option>Organic</option><option>Mixed Recyclables</option></select></label></div><label>Pickup address<textarea name="address" required placeholder="House number, road, city"/></label><div className="form-pair"><label>Estimated quantity<input name="quantity" required placeholder="e.g. 3 bags"/></label><label>Preferred date<input name="pickupDate" type="date" required/></label></div><div className="form-pair"><label>Preferred time<input name="pickupTime" type="time" required/></label><label>Notes<input name="notes" placeholder="Gate colour, landmark…"/></label></div><button className="system-primary" disabled={busy}>♻ Submit pickup request</button></form><div className="system-card"><h3>Recent requests</h3><RequestList requests={data.requests}/></div></div></section>
}

function CollectorView({data,collector,collectorId,setCollectorId,balance,busy,act}:{data:Data;collector?:Collector;collectorId:string;setCollectorId:(v:string)=>void;balance:number;busy:boolean;act:(p:Record<string,unknown>,s:string)=>Promise<void>}){
  const pending=data.requests.filter(r=>r.status==="Pending");const assigned=data.requests.filter(r=>r.collector_id===collectorId&&r.status==="Scheduled");const completed=data.requests.filter(r=>r.collector_id===collectorId&&r.status==="Completed");
  function register(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;void act({action:"registerCollector",...Object.fromEntries(new FormData(form))},"Registration sent for admin verification.").then(()=>form.reset());}
  return <section className="system-workspace"><div className="collector-head"><div><small>COLLECTOR PORTAL</small><h2>Collection jobs & rewards</h2><p>100 coins are credited only after a scheduled pickup is completed.</p></div><div className="coin-card"><small>AVAILABLE BALANCE</small><strong>🪙 {balance}</strong><span>Collector coins</span></div></div>
    <div className="collector-select"><label>Active collector<select value={collectorId} onChange={e=>setCollectorId(e.target.value)}><option value="">Select profile</option>{data.collectors.map(c=><option value={c.id} key={c.id}>{c.name} — {c.verification_status}</option>)}</select></label>{collector&&<span className={collector.verification_status==="Verified"?"status completed":"status pending"}>{collector.verification_status}</span>}</div>
    <div className="system-columns"><form className="system-card system-form compact" onSubmit={register}><h3>Register as a collector</h3><label>Name<input name="name" required/></label><label>Phone<input name="phone" required/></label><label>Service area<input name="serviceArea" required placeholder="e.g. Chilaw"/></label><label>Organization<input name="organization" placeholder="Independent Collector"/></label><button className="system-primary" disabled={busy}>Send for verification</button></form><div className="system-card"><h3>Available pickup requests</h3>{pending.length===0?<Empty text="No open pickup requests right now."/>:<div className="job-list">{pending.map(r=><article key={r.id}><div><b>{r.waste_type}</b><span className="status pending">Pending</span></div><p>📍 {r.address}</p><small>{r.pickup_date} · {r.pickup_time} · {r.quantity}</small><button disabled={busy||collector?.verification_status!=="Verified"} onClick={()=>void act({action:"acceptRequest",requestId:r.id,collectorId},"Pickup accepted.")}>Accept job</button></article>)}</div>}</div></div>
    <div className="system-card wide"><h3>My scheduled collections</h3>{assigned.length===0?<Empty text="Accepted jobs will appear here."/>:<div className="job-list job-grid">{assigned.map(r=><article key={r.id}><div><b>{r.household_name}</b><span className="status scheduled">Scheduled</span></div><p>{r.address}</p><small>{r.pickup_date} · {r.pickup_time}</small><CompleteForm request={r} collectorId={collectorId} busy={busy} act={act}/></article>)}</div>}</div>
    <div className="rewards-system"><div><p className="kicker">COLLECTOR REWARDS</p><h2>Redeem your coins</h2><p>Households do not earn Eco Points. These rewards are exclusively for verified collection work.</p></div><div className="system-reward-grid">{rewards.map(r=><article key={r.name}><span>{r.icon}</span><h3>{r.name}</h3><strong>{r.points} coins</strong><button disabled={busy||!collectorId||balance<r.points} onClick={()=>void act({action:"redeem",collectorId,rewardName:r.name,points:r.points},`${r.name} redeemed successfully.`)}>{balance>=r.points?"Redeem":"More coins needed"}</button></article>)}</div>{completed.length>0&&<p className="completion-note">✓ {completed.length} completed collection{completed.length===1?"":"s"} · {completed.length*100} coins earned before redemptions</p>}</div>
  </section>
}

function CompleteForm({request,collectorId,busy,act}:{request:Pickup;collectorId:string;busy:boolean;act:(p:Record<string,unknown>,s:string)=>Promise<void>}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const v=Object.fromEntries(new FormData(f));void act({action:"completeRequest",requestId:request.id,collectorId,...v},"Collection completed — 100 coins added.");}return <form className="complete-form" onSubmit={submit}><select name="wasteType" defaultValue={request.waste_type}><option>Plastic</option><option>Paper & Cardboard</option><option>Metal</option><option>Glass</option><option>E-Waste</option><option>Organic</option><option>Mixed Recyclables</option></select><input name="weight" type="number" min="0.1" step="0.1" required placeholder="Weight (kg)"/><button disabled={busy}>Complete +100</button></form>}

function Admin({data,busy,act}:{data:Data;busy:boolean;act:(p:Record<string,unknown>,s:string)=>Promise<void>}){const waiting=data.collectors.filter(c=>c.verification_status!=="Verified");return <section className="system-workspace"><div className="system-intro"><div><small>ADMIN PORTAL</small><h2>Verify and monitor operations</h2><p>Collector approval protects households and unlocks job acceptance.</p></div><div className="admin-metrics"><span><b>{data.requests.length}</b> requests</span><span><b>{data.collectors.length}</b> collectors</span><span><b>{data.requests.filter(r=>r.status==="Completed").length}</b> completed</span></div></div><div className="system-columns"><div className="system-card"><h3>Collector verification</h3>{waiting.length===0?<Empty text="No collectors are waiting for verification."/>:<div className="job-list">{waiting.map(c=><article key={c.id}><div><b>{c.name}</b><span className="status pending">Pending</span></div><p>{c.organization} · {c.service_area}</p><small>{c.phone}</small><button disabled={busy} onClick={()=>void act({action:"verifyCollector",collectorId:c.id},`${c.name} is now verified.`)}>Verify collector</button></article>)}</div>}</div><div className="system-card"><h3>All pickup requests</h3><RequestList requests={data.requests}/></div></div></section>}

function RequestList({requests}:{requests:Pickup[]}){return requests.length===0?<Empty text="No pickup requests yet."/>:<div className="request-list">{requests.map(r=><article key={r.id}><div><b>{r.waste_type}</b><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></div><p>{r.household_name} · {r.address}</p><small>{r.pickup_date} at {r.pickup_time}{r.collector_name?` · ${r.collector_name}`:""}</small></article>)}</div>}
function Empty({text}:{text:string}){return <div className="system-empty"><span>♻</span><p>{text}</p></div>}
